prefix dicom:  <http://purl.org/healthcarevocab/v1/>
PREFIX sc: <http://purl.org/science/owl/sciencecommons/>
prefix ep:     <http://example.org/electronicproduct/>
prefix ex:     <http://example.com/>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix schema: <http://schema.org/>
prefix xsd:    <http://www.w3.org/2001/XMLSchema#>
prefix dbpedia-owl:  <http://debpedia.org/ontology/>

SELECT DISTINCT ?brandTel ?brandEP
WHERE {
    ?upc dicom:ProductName ?pName;
         schema:brand ?brandTel.
    ?s schema:brand ?brandEP.
    ?brandEP schema:name ?brandEPname.
    FILTER (STRENDS(UCASE(STR(?brandTel)),UCASE(?brandEPname))).
}

SELECT DISTINCT ?brandTel ?brandEP
WHERE {
    ?upc dicom:ProductName ?pName;
         schema:brand ?brandTel.
    ?s schema:brand ?brandEP;
       schema:category "Mobile".
    ?brandEP schema:name ?brandEPname.
    FILTER (STRENDS(UCASE(STR(?brandTel)),UCASE(?brandEPname))).
}